# Generated by Django 5.1.7 on 2025-04-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.CharField(max_length=255)),
                ('user_fullname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('action', models.CharField(choices=[('add', 'Ajout'), ('update', 'Modification'), ('delete', 'Suppression')], max_length=10)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('object_name', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
