# Generated by Django 5.1.7 on 2025-03-31 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_commande_panier_user_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panieritem',
            name='panier',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='user',
        ),
        migrations.AddField(
            model_name='commande',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='commande',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Panier',
        ),
        migrations.DeleteModel(
            name='PanierItem',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
