# Generated by Django 5.1.7 on 2025-04-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
