# Generated by Django 5.1.7 on 2025-04-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_address_order_fullname_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='statut',
            field=models.CharField(choices=[('pending', 'En entente'), ('validated', 'Validée')], default='pending', max_length=20),
        ),
    ]
